server.port=4002

spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5000/db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

jwt.secret=dev-only-secret-key-change-me-please-1234567890
jwt.expiration-ms=3600000
