services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql # Mounts top-level postgres directory required by PG 18+

  # patient-service:
  #   build:
  #     context: ./patient-service
  #     dockerfile: Dockerfile
  #   container_name: patient-service
  #   ports:
  #     - "4000:4000"
  #   labels:
  #     - "org.springframework.boot.ignore=true"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
  #     SPRING_DATASOURCE_USERNAME: admin_user
  #     SPRING_DATASOURCE_PASSWORD: password
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     SPRING_SQL_INIT_MODE: always
  #     SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  #   depends_on:
  #     patient-service-db:
  #       condition: service_healthy
  #   networks:
  #     - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data: