server.port=4001

spring.application.name=appointment-service

patient.service.url=http://localhost:4000

spring.datasource.url=jdbc:postgresql://localhost:5000/db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.client-id=appointment-service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.max.block.ms=5000
